[2022-10-05 15:22:28,388] {processor.py:153} INFO - Started process (PID=479) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:28,389] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:22:28,391] {logging_mixin.py:115} INFO - [2022-10-05 15:22:28,391] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:28,427] {logging_mixin.py:115} INFO - [2022-10-05 15:22:28,424] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 4, in <module>
    from plugins import dataflow
ModuleNotFoundError: No module named 'plugins'
[2022-10-05 15:22:28,429] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:28,473] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.094 seconds
[2022-10-05 15:22:58,629] {processor.py:153} INFO - Started process (PID=543) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:58,631] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:22:58,633] {logging_mixin.py:115} INFO - [2022-10-05 15:22:58,633] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:58,654] {logging_mixin.py:115} INFO - [2022-10-05 15:22:58,652] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 4, in <module>
    from plugins import dataflow
ModuleNotFoundError: No module named 'plugins'
[2022-10-05 15:22:58,655] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:22:58,697] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.075 seconds
[2022-10-05 15:23:24,634] {processor.py:153} INFO - Started process (PID=587) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:24,641] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:23:24,645] {logging_mixin.py:115} INFO - [2022-10-05 15:23:24,644] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:24,737] {logging_mixin.py:115} INFO - [2022-10-05 15:23:24,732] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 4, in <module>
    from plugins import dataflow
ModuleNotFoundError: No module named 'plugins'
[2022-10-05 15:23:24,741] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:24,853] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.239 seconds
[2022-10-05 15:23:34,601] {processor.py:153} INFO - Started process (PID=604) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:34,605] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:23:34,610] {logging_mixin.py:115} INFO - [2022-10-05 15:23:34,609] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:34,643] {logging_mixin.py:115} INFO - [2022-10-05 15:23:34,640] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:23:34,654] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:34,793] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.208 seconds
[2022-10-05 15:23:40,228] {processor.py:153} INFO - Started process (PID=619) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:40,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:23:40,249] {logging_mixin.py:115} INFO - [2022-10-05 15:23:40,249] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:40,321] {logging_mixin.py:115} INFO - [2022-10-05 15:23:40,316] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 4, in <module>
    from plugins import dataflow
ModuleNotFoundError: No module named 'plugins'
[2022-10-05 15:23:40,324] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:40,468] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.257 seconds
[2022-10-05 15:23:42,852] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:42,856] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:23:42,862] {logging_mixin.py:115} INFO - [2022-10-05 15:23:42,862] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:43,082] {logging_mixin.py:115} INFO - [2022-10-05 15:23:43,079] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:23:43,089] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:23:43,400] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.568 seconds
[2022-10-05 15:24:13,615] {processor.py:153} INFO - Started process (PID=679) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:13,617] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:24:13,619] {logging_mixin.py:115} INFO - [2022-10-05 15:24:13,619] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:13,631] {logging_mixin.py:115} INFO - [2022-10-05 15:24:13,629] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:24:13,632] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:13,673] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.065 seconds
[2022-10-05 15:24:43,837] {processor.py:153} INFO - Started process (PID=734) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:43,839] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:24:43,841] {logging_mixin.py:115} INFO - [2022-10-05 15:24:43,840] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:43,849] {logging_mixin.py:115} INFO - [2022-10-05 15:24:43,848] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:24:43,850] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:24:43,901] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.069 seconds
[2022-10-05 15:25:14,399] {processor.py:153} INFO - Started process (PID=799) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:14,402] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:25:14,404] {logging_mixin.py:115} INFO - [2022-10-05 15:25:14,404] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:14,418] {logging_mixin.py:115} INFO - [2022-10-05 15:25:14,415] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:25:14,420] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:14,462] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.069 seconds
[2022-10-05 15:25:44,670] {processor.py:153} INFO - Started process (PID=855) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:44,673] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:25:44,675] {logging_mixin.py:115} INFO - [2022-10-05 15:25:44,675] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:44,685] {logging_mixin.py:115} INFO - [2022-10-05 15:25:44,684] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:25:44,687] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:25:44,728] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.065 seconds
[2022-10-05 15:26:15,158] {processor.py:153} INFO - Started process (PID=918) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:15,160] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:26:15,162] {logging_mixin.py:115} INFO - [2022-10-05 15:26:15,162] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:15,169] {logging_mixin.py:115} INFO - [2022-10-05 15:26:15,168] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:26:15,171] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:15,227] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.076 seconds
[2022-10-05 15:26:45,467] {processor.py:153} INFO - Started process (PID=974) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:45,469] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:26:45,471] {logging_mixin.py:115} INFO - [2022-10-05 15:26:45,471] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:45,479] {logging_mixin.py:115} INFO - [2022-10-05 15:26:45,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:26:45,480] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:26:45,511] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.049 seconds
[2022-10-05 15:27:15,898] {processor.py:153} INFO - Started process (PID=1035) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:15,900] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:27:15,902] {logging_mixin.py:115} INFO - [2022-10-05 15:27:15,901] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:15,909] {logging_mixin.py:115} INFO - [2022-10-05 15:27:15,908] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:27:15,911] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:15,952] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.058 seconds
[2022-10-05 15:27:46,045] {processor.py:153} INFO - Started process (PID=1091) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:46,047] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:27:46,049] {logging_mixin.py:115} INFO - [2022-10-05 15:27:46,049] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:46,056] {logging_mixin.py:115} INFO - [2022-10-05 15:27:46,055] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:27:46,057] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:27:46,088] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.048 seconds
[2022-10-05 15:28:16,161] {processor.py:153} INFO - Started process (PID=1156) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:16,164] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:28:16,167] {logging_mixin.py:115} INFO - [2022-10-05 15:28:16,166] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:16,179] {logging_mixin.py:115} INFO - [2022-10-05 15:28:16,177] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:28:16,181] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:16,236] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.083 seconds
[2022-10-05 15:28:46,736] {processor.py:153} INFO - Started process (PID=1211) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:46,740] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:28:46,743] {logging_mixin.py:115} INFO - [2022-10-05 15:28:46,743] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:46,762] {logging_mixin.py:115} INFO - [2022-10-05 15:28:46,759] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:28:46,765] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:28:46,835] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.111 seconds
[2022-10-05 15:29:17,600] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:17,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:29:17,605] {logging_mixin.py:115} INFO - [2022-10-05 15:29:17,605] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:17,617] {logging_mixin.py:115} INFO - [2022-10-05 15:29:17,615] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:29:17,619] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:17,683] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.090 seconds
[2022-10-05 15:29:48,376] {processor.py:153} INFO - Started process (PID=1332) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:48,379] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:29:48,381] {logging_mixin.py:115} INFO - [2022-10-05 15:29:48,380] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:48,390] {logging_mixin.py:115} INFO - [2022-10-05 15:29:48,389] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:29:48,391] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:29:48,438] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.067 seconds
[2022-10-05 15:30:19,187] {processor.py:153} INFO - Started process (PID=1388) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:19,189] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:30:19,191] {logging_mixin.py:115} INFO - [2022-10-05 15:30:19,191] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:19,199] {logging_mixin.py:115} INFO - [2022-10-05 15:30:19,198] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:30:19,200] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:19,244] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.066 seconds
[2022-10-05 15:30:49,872] {processor.py:153} INFO - Started process (PID=1453) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:49,874] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:30:49,876] {logging_mixin.py:115} INFO - [2022-10-05 15:30:49,876] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:49,885] {logging_mixin.py:115} INFO - [2022-10-05 15:30:49,883] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:30:49,886] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:30:49,924] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.058 seconds
[2022-10-05 15:31:20,646] {processor.py:153} INFO - Started process (PID=1509) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:20,655] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:31:20,671] {logging_mixin.py:115} INFO - [2022-10-05 15:31:20,671] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:20,711] {logging_mixin.py:115} INFO - [2022-10-05 15:31:20,708] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:31:20,713] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:20,847] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.228 seconds
[2022-10-05 15:31:23,846] {processor.py:153} INFO - Started process (PID=1512) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:23,850] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:31:23,853] {logging_mixin.py:115} INFO - [2022-10-05 15:31:23,853] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:23,880] {logging_mixin.py:115} INFO - [2022-10-05 15:31:23,876] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:31:23,883] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:23,965] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.131 seconds
[2022-10-05 15:31:30,601] {processor.py:153} INFO - Started process (PID=1527) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:30,609] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:31:30,617] {logging_mixin.py:115} INFO - [2022-10-05 15:31:30,616] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:30,652] {logging_mixin.py:115} INFO - [2022-10-05 15:31:30,649] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:31:30,659] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:31:30,772] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.202 seconds
[2022-10-05 15:32:01,503] {processor.py:153} INFO - Started process (PID=1573) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:01,507] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:32:01,512] {logging_mixin.py:115} INFO - [2022-10-05 15:32:01,511] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:01,531] {logging_mixin.py:115} INFO - [2022-10-05 15:32:01,528] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:32:01,537] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:01,651] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.191 seconds
[2022-10-05 15:32:32,429] {processor.py:153} INFO - Started process (PID=1638) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:32,432] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:32:32,433] {logging_mixin.py:115} INFO - [2022-10-05 15:32:32,433] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:32,440] {logging_mixin.py:115} INFO - [2022-10-05 15:32:32,439] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:32:32,441] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:32:32,473] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.049 seconds
[2022-10-05 15:33:02,984] {processor.py:153} INFO - Started process (PID=1694) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:02,986] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:33:02,988] {logging_mixin.py:115} INFO - [2022-10-05 15:33:02,988] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:02,997] {logging_mixin.py:115} INFO - [2022-10-05 15:33:02,996] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:33:02,998] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:03,028] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.049 seconds
[2022-10-05 15:33:33,201] {processor.py:153} INFO - Started process (PID=1760) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:33,203] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:33:33,205] {logging_mixin.py:115} INFO - [2022-10-05 15:33:33,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:33,213] {logging_mixin.py:115} INFO - [2022-10-05 15:33:33,212] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:33:33,214] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:33:33,246] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.050 seconds
[2022-10-05 15:34:03,837] {processor.py:153} INFO - Started process (PID=1814) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:03,840] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:34:03,844] {logging_mixin.py:115} INFO - [2022-10-05 15:34:03,844] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:03,857] {logging_mixin.py:115} INFO - [2022-10-05 15:34:03,856] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:34:03,859] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:03,902] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.072 seconds
[2022-10-05 15:34:34,601] {processor.py:153} INFO - Started process (PID=1879) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:34,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:34:34,605] {logging_mixin.py:115} INFO - [2022-10-05 15:34:34,605] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:34,612] {logging_mixin.py:115} INFO - [2022-10-05 15:34:34,611] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:34:34,613] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:34:34,643] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.047 seconds
[2022-10-05 15:35:05,002] {processor.py:153} INFO - Started process (PID=1942) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:05,005] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:35:05,006] {logging_mixin.py:115} INFO - [2022-10-05 15:35:05,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:05,012] {logging_mixin.py:115} INFO - [2022-10-05 15:35:05,011] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:35:05,013] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:05,045] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.048 seconds
[2022-10-05 15:35:35,209] {processor.py:153} INFO - Started process (PID=1998) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:35,211] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:35:35,214] {logging_mixin.py:115} INFO - [2022-10-05 15:35:35,213] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:35,225] {logging_mixin.py:115} INFO - [2022-10-05 15:35:35,223] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:35:35,226] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:35:35,274] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.072 seconds
[2022-10-05 15:51:17,060] {processor.py:153} INFO - Started process (PID=2031) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:17,062] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:51:17,066] {logging_mixin.py:115} INFO - [2022-10-05 15:51:17,066] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:17,093] {logging_mixin.py:115} INFO - [2022-10-05 15:51:17,089] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:51:17,095] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:17,159] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.105 seconds
[2022-10-05 15:51:48,096] {processor.py:153} INFO - Started process (PID=2087) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:48,097] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:51:48,099] {logging_mixin.py:115} INFO - [2022-10-05 15:51:48,099] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:48,106] {logging_mixin.py:115} INFO - [2022-10-05 15:51:48,105] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:51:48,107] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:51:48,132] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.040 seconds
[2022-10-05 15:52:18,543] {processor.py:153} INFO - Started process (PID=2152) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:18,544] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:52:18,547] {logging_mixin.py:115} INFO - [2022-10-05 15:52:18,547] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:18,556] {logging_mixin.py:115} INFO - [2022-10-05 15:52:18,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:52:18,557] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:18,599] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.063 seconds
[2022-10-05 15:52:48,938] {processor.py:153} INFO - Started process (PID=2217) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:48,940] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:52:48,941] {logging_mixin.py:115} INFO - [2022-10-05 15:52:48,941] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:48,949] {logging_mixin.py:115} INFO - [2022-10-05 15:52:48,947] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:52:48,950] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:52:48,975] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.042 seconds
[2022-10-05 15:53:19,294] {processor.py:153} INFO - Started process (PID=2273) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:19,295] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:53:19,296] {logging_mixin.py:115} INFO - [2022-10-05 15:53:19,296] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:19,302] {logging_mixin.py:115} INFO - [2022-10-05 15:53:19,301] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:53:19,303] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:19,329] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.039 seconds
[2022-10-05 15:53:49,775] {processor.py:153} INFO - Started process (PID=2338) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:49,777] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 15:53:49,780] {logging_mixin.py:115} INFO - [2022-10-05 15:53:49,779] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:49,786] {logging_mixin.py:115} INFO - [2022-10-05 15:53:49,785] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 15:53:49,787] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 15:53:49,813] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.043 seconds
[2022-10-05 16:01:50,159] {processor.py:153} INFO - Started process (PID=2371) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:01:50,161] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:01:50,163] {logging_mixin.py:115} INFO - [2022-10-05 16:01:50,163] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:01:50,177] {logging_mixin.py:115} INFO - [2022-10-05 16:01:50,175] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:01:50,178] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:01:50,300] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.148 seconds
[2022-10-05 16:03:19,581] {processor.py:153} INFO - Started process (PID=2417) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:03:19,587] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:03:19,601] {logging_mixin.py:115} INFO - [2022-10-05 16:03:19,601] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:03:19,618] {logging_mixin.py:115} INFO - [2022-10-05 16:03:19,617] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:03:19,619] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:03:19,734] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.158 seconds
[2022-10-05 16:14:13,097] {processor.py:153} INFO - Started process (PID=2448) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:14:13,122] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:14:13,128] {logging_mixin.py:115} INFO - [2022-10-05 16:14:13,128] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:14:13,206] {logging_mixin.py:115} INFO - [2022-10-05 16:14:13,178] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:14:13,208] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:14:13,391] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.304 seconds
[2022-10-05 16:15:16,963] {processor.py:153} INFO - Started process (PID=2494) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:15:16,971] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:15:16,975] {logging_mixin.py:115} INFO - [2022-10-05 16:15:16,975] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:15:17,020] {logging_mixin.py:115} INFO - [2022-10-05 16:15:17,019] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:15:17,024] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:15:17,710] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.768 seconds
[2022-10-05 16:16:50,214] {processor.py:153} INFO - Started process (PID=2541) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:16:50,216] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:16:50,224] {logging_mixin.py:115} INFO - [2022-10-05 16:16:50,224] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:16:50,246] {logging_mixin.py:115} INFO - [2022-10-05 16:16:50,245] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:16:50,292] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:16:50,488] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.282 seconds
[2022-10-05 16:18:32,749] {processor.py:153} INFO - Started process (PID=2588) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:18:32,563] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 16:18:32,574] {logging_mixin.py:115} INFO - [2022-10-05 16:18:32,573] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:18:32,597] {logging_mixin.py:115} INFO - [2022-10-05 16:18:32,595] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 16:18:32,600] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 16:18:32,905] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 1.079 seconds
[2022-10-05 18:02:49,724] {processor.py:153} INFO - Started process (PID=2635) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 18:02:49,727] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 18:02:49,912] {logging_mixin.py:115} INFO - [2022-10-05 18:02:49,904] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 18:02:49,938] {logging_mixin.py:115} INFO - [2022-10-05 18:02:49,935] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 18:02:49,942] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 18:02:50,329] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.674 seconds
[2022-10-05 20:03:22,600] {processor.py:153} INFO - Started process (PID=2692) to work on /opt/airflow/dags/run_dataflow.py
[2022-10-05 20:03:22,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/run_dataflow.py for tasks to queue
[2022-10-05 20:03:22,606] {logging_mixin.py:115} INFO - [2022-10-05 20:03:22,605] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/run_dataflow.py
[2022-10-05 20:03:22,640] {logging_mixin.py:115} INFO - [2022-10-05 20:03:22,628] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/run_dataflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/run_dataflow.py", line 20
    )
    ^
SyntaxError: invalid syntax
[2022-10-05 20:03:22,642] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/run_dataflow.py
[2022-10-05 20:03:22,783] {processor.py:161} INFO - Processing /opt/airflow/dags/run_dataflow.py took 0.214 seconds
